[package]
name = "solution"
version = "0.1.0"

[dependencies]
chrono = "0.4.1"
flexi_logger = "0.8.1"
lazy_static = "1.0.0"
log = "0.4.1"
num-traits = "0.2.2"
proc-macro2 = "0.3.5"
quote = "0.5.1"
rand = "0.4.2"
serde = "1.0.13"
serde_derive = "1.0.13"
serde_json = "1.0.13"
syn = "0.13.1"
